name: Worker Deploy
on:
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: api-facade/package-lock.json

      - name: Install deps (api-facade)
        working-directory: api-facade
        run: |
          if [ -f package-lock.json ]; then
            npm ci --omit=dev
          else
            npm i --omit=dev
          fi

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: api-facade
          command: deploy
