name: Worker Deploy
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Worker name (e.g., fitness-api-staging)"
        required: true
        default: "fitness-api-staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Wrangler Action
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: api-facade
          command: deploy --name "${{ github.event.inputs.env }}"
